val table = hashMapOf<String,Int>()

fun initTable(){
    table.apply {
        put("begin",1)
        put("end",2)
        put("if",3)
        put("then",4)
        put("else",5)
        put("while",6)
        put("do",7)
        put("identifier",10)
        put("number",11)
        put("+",13)
        put("-",14)
        put("*",15)
        put("/",16)
        put("#",18)
        put(":=",19)
        put(":",20)
        put("=",21)
        put("+",22)
        put("-",23)
        put("*",24)
        put("/",25)
        put("(",26)
        put(")",27)
        put("[",28)
        put("]",29)
        put("{",30)
        put("}",31)
        put(",",32)
        put(":",33)
        put(";",34)
        put("<",36)
        put(">",35)
        put(">=",37)
        put("<=",38)
        put("==",39)
        put("!=",40)
    }
}